#Open file

In [35]:
import csv
import itertools
import numpy as np
import math
import os
import glob

#step2 複数フレームから1つに圧縮！？

#txtからcsvへ，LED検出
direct='right'#change! left or right
dstnc=['1','4','5']  
if direct == 'right':
    dire = 'R'
else:
    dire = 'L'
nnn=f"//TS5410DFCD/share/01_yasui/BER_{direct}" 

In [36]:
#OK!
####    RGB値をxy座標に置き換える　＆　チャネル行列で補正
for q in range(3):
    correct = 0

    videos=[]
    for i in range(1,11):
        videos.append('4CSK_{}_{}{}'.format(dstnc[q],dire,str(i))) #1 change/ R or L

    for i in range(10):

        # path = './test_156m.csv'
        name = f"{nnn}/{videos[i]}"
        path=f"{name}/{videos[i]}_sync.csv" #sync.csv"

        print(path)

        if not os.path.isdir("{}/graph".format(name)):
            os.makedirs("{}/graph".format(name))



        with open(path, 'r') as f:
            reader = csv.reader(f)
            res = [row for row in reader]

        for row in res:
            row[:] = map(int, row)


        R = [res[0][0],res[1][0],res[2][0]]
        G = [res[0][1],res[1][1],res[2][1]]
        B = [res[0][2],res[1][2],res[2][2]]


        R[0] -= correct
        G[1] -= correct
        B[2] -= 0
        # r = 223
        # g = 220
        # b = 224

        B = np.array([R, G, B])
        print(B)
        # A = np.matrix([[1,-1,-1],[-1,1,-1],[-1,-1,1]])
        A = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

        H = np.dot(B, np.linalg.inv(A))
        # H_inv = np.linalg.inv(H)
        H_inv = np.linalg.pinv(H)

        print(H)
        print(H_inv)

        # re = np.array([[r],[g],[b]])
        # ans = np.dot(H_inv , re)

        # print(ans)


        # path = './test_156m.csv'


        with open(path, 'r') as f:
            reader = csv.reader(f)
            res = [row for row in reader]

        for row in res:
            row[:] = map(int, row)

        # print(res)

        # make_path=f"{nnn}/graph"
        # if not os.path.exists(make_path):
        #     os.mkdir(make_path)

        folder=name

        with open(f"{folder}/graph/xy.csv", 'w') as f:
            f.write('')


        path = f"{folder}/graph/theory.txt"
        with open(path, 'w') as f:
            f.write('')


        with open(f"{folder}/graph/xy.csv", 'w') as f:
            f.write('')

        for i in range(len(res)):
            #     print([[res[i][0]],[res[i][1]],[res[i][2]]])
            re = np.array([[res[i][0]+0], [res[i][1]-0], [res[i][2]+0]])
            ans = np.dot(H_inv, re)   #チャネル行列使用する'''
            # ans=re  #チャネル行列使用しない'''
        #     print(ans[0][0])
            # ans = normalize(ans,axis = 0)
            for j in range(len(ans)):
                if ans[j][0] < 0:
                    ans[j][0] = 0
            ans = ans/np.sum(ans)
            x = 0.65*ans[0][0] + 0.3 * ans[1][0] + 0.15 * ans[2][0]
            y = 0.3*ans[0][0] + 0.6 * ans[1][0] + 0.05 * ans[2][0]
            with open(path, 'a') as f:
                f.write(str(x))
                f.write('\t')
                f.write(str(y))
                f.write('\n')

            with open(f"{folder}/graph/xy.csv", 'a') as f:
                f.write(str(x))
                f.write(',')
                f.write(str(y))
                f.write('\n')


        with open(f'{folder}/graph/red.txt', 'w') as f:
            f.write('')

        with open(f'{folder}/graph/green.txt', 'w') as f:
            f.write('')

        with open(f'{folder}/graph/blue.txt', 'w') as f:
            f.write('')

        with open(f'{folder}/graph/white.txt', 'w') as f:
            f.write('')

        with open(f"{folder}/graph/result.txt", 'w') as ff:
            ff.write('')


        with open(f"{folder}/graph/xy.csv", 'r') as f:
            reader = csv.reader(f)
            res = [row for row in reader]

        for row in res:
            row[:] = map(float, row)

        # print(res)
        #x = [0.65,  0.3,    0.15,   0.275,  0.4,    0.225,  0.4,    0.5,    0.36]
        #y = [0.3,   0.6,    0.05,   0.45,   0.5,    0.2,    0.2,    0.35,   0.35]

        # x = [0.65,  0.3,   0.15,   0.275,	0.4, 0.25,   0.4,	0.5]
        # y = [0.3,	0.6,   0.05,   0.4,	0.45,   0.2,	0.2,	0.35]

        x = [0.65,  0.3,   0.15,   0.37]
        y = [0.3,	0.6,   0.05,   0.32]
        ans = [0 for i in range(len(x))]

        #9csk result="012345678015325381713245165817057615452348731264138505674375817563603876762518456385352813118657128436834717287083045815410681736684417807284007285672785464821768272132387378210336805804148601426857351608317681037138436372542453"
        #8csk 
        # result = "012345670153253171324516517057615452347312641350567437517563603767625145635352131165712436347172703045154106173664417072400725672754642176272132373721033605041460142657351603176103713436372542453"
        
        #4csk
        result="01230212132323030321212320302030120303212030212023012302121323230303212123203020301203032120302120230123021213232303032121232030203012030321203021202301230212132323030321212320302030120303212030212023"

        #6coloe
        # result="01232560153253101325165105061525232031262135056023051056360306062512563535213165012363201020302515210610362102025602052621062021323030210360502126012650351603106103013236302525"

        #display用
        #result="013560535173456175614237124355747176607765453351115123341273455101364177407562544172212732036501604653163760714632425"

        tmpp = ["red", "green", "blue",  "white"]

        # print(tmpp[1])
        for i in range(int(len(res))):
            for j in range(len(x)):
                ans[j] = math.sqrt(pow(res[i][0]-x[j], 2) + pow(res[i][1]-y[j], 2))
            min = np.min(ans)
            tmp = np.where(ans == min)
            # print(tmp[0][0])

            with open(f"{folder}/graph/result.txt", 'a') as ff:
                ff.write(str(tmp[0][0]))
                ff.write('\n')
            
            if i<len(result):
                with open(f'{folder}/graph/{tmpp[int(result[i])]}.txt', 'a') as f: 
                    f.write(str(res[i][0]))
                    f.write('\t')
                    f.write(str(res[i][1]))
                    f.write('\n')



//TS5410DFCD/share/01_yasui/BER_right/4CSK_1_R1/4CSK_1_R1_sync.csv
[[226 226 226]
 [ 26  26  27]
 [ 88  90  88]]
[[226. 226. 226.]
 [ 26.  26.  27.]
 [ 88.  90.  88.]]
[[ 3.14159292e-01 -1.00000000e+00 -5.00000000e-01]
 [-1.94690265e-01  4.90232741e-15  5.00000000e-01]
 [-1.15044248e-01  1.00000000e+00  1.75411478e-15]]
//TS5410DFCD/share/01_yasui/BER_right/4CSK_1_R2/4CSK_1_R2_sync.csv
[[227  43  94]
 [ 16 175  94]
 [ 98  56 227]]
[[227.  43.  94.]
 [ 16. 175.  94.]
 [ 98.  56. 227.]]
[[ 0.00527353 -0.00068817 -0.00189878]
 [ 0.0008539   0.00647573 -0.00303518]
 [-0.00248733 -0.00130044  0.00597379]]
//TS5410DFCD/share/01_yasui/BER_right/4CSK_1_R3/4CSK_1_R3_sync.csv
[[233  85 120]
 [ 29 136  89]
 [ 90  63 183]]
[[233.  85. 120.]
 [ 29. 136.  89.]
 [ 90.  63. 183.]]
[[ 0.00555222 -0.00230226 -0.00252112]
 [ 0.00077836  0.00916845 -0.00496938]
 [-0.00299856 -0.00202409  0.00841514]]
//TS5410DFCD/share/01_yasui/BER_right/4CSK_1_R4/4CSK_1_R4_sync.csv
[[128 236 234]
 [ 88  27  32]
 [179  93